name: infopessoas
description: "InfoPessoas - Flutter"


publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  dio: ^5.9.0
  sqflite: ^2.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7


flutter:
  uses-material-design: true

  assets:
    - assets/logos/


  fonts:
  - family: Outfit
    fonts:
      - asset: assets/fonts/Outfit-Regular.ttf
        weight: 400
      - asset: assets/fonts/Outfit-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Outfit-Bold.ttf
        weight: 700



flutter_native_splash:
  android: true
  ios: true

  color: "#1D594E"
  image: assets/logos/splash.png

  android_12:
    color: "#1D594E"
    image: assets/logos/splash.png
    icon_background_color: "#1D594E"